### ISSUE TITLE
Create pages and implement campaign search

### ISSUE THREAD

**Issue by bocaaust** [bocaaust/CrowdCop#17]

**Comment by kburk1997** [comment]
The campaign search is now working!

Run the following on the server:
pip uninstall django-haystack
pip install git+https://github.com/django-haystack/django-haystack.git

**Comment by bocaaust** [comment]
Had to also install git

Proper command  for installing haystacks from github

pip install -e git+
https://github.com/toastdriven/django-haystack.git@master#egg=django-haystack

On Sun, May 8, 2016 at 3:58 PM, Kathleen Burkhardt <notifications@github.com
