### ISSUE TITLE
Fix captcha on web server

### ISSUE THREAD

**Issue by kburk1997** [bocaaust/CrowdCop#19]
On the localhost, the captcha is showing up fine on the "submit a tip" page. However, this does not reflect on the server

**Comment by bocaaust** [comment]
This is probably because it is using a module I didn't install. Need you to generate requirements.txt when it is running properly on local host

**Comment by bocaaust** [comment]
Can't test tip page because of captcha problems

**Comment by bocaaust** [comment]
I fixed by installing libfreetype
