### ISSUE TITLE
Error during template rendering

### ISSUE THREAD

**Issue by bocaaust** [bocaaust/CrowdCop#23]
Reverse for 'trending' with arguments '()' and keyword arguments '{u'page': ''}' not found. 1 pattern(s) tried: ['crowdcop_web/trending/(?P<page>[0-9]+)/$']

This is related to your trending implementation.

**Comment by kburk1997** [comment]
I just fixed this loading of the index, however on my test machine staticfiles won't load.

**Comment by kburk1997** [comment]
This works on both the localhost and the server, just in time for the UGRS!
